# -*- coding: utf-8 -*-
"""Mision2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nOMXnmRufTS3OyMhNhDA0JP-g1RUdWFy
"""

import pandas as pd

df = pd.read_excel('/estadistica.xlsx')

print(df)

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import matplotlib.pyplot as plt

datosAnos = {'anos': [2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]}
datosColombia = {'colombia': [80.1697,  80.6008,  81.5337,  84.0109,  72.8779,  72.1207,  83.4653, 79.5502,  69.4201,  69.2963,  64.0221,  65.9042,  79.3820,  76.8500, 70.0900, 65.7900, 73.4200, 75.0700]}

#generacion electrica de colombia

import pandas as pd

df = pd.DataFrame(datosAnos)
dg = pd.DataFrame(datosColombia)

print(df)
print(dg)

import matplotlib.pyplot as plt

plt.plot(df, dg, 'o--r')

plt.title("Generación eléctrica de Colombia", pad=30)
plt.xlabel("Años")
plt.ylabel("TWh")

plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array(["Argentina", "Brasil", "Chile", "Colombia", "Perú","Venezuela"])
y = np.array([26.70, 82.73, 45.28, 74.37, 56.50, 69.24])

plt.title("Promedio de energia electrica renovable de colombia comparada con algunos paises de sur-america en Porcentajes 2005-2022")

bars = plt.bar(x, y)


plt.xlabel("Paises")
plt.ylabel("Porcentaje")

# Cambiar el color y contorno de la barra de "Colombia" (la cuarta barra, índice 3)
colombia_bar = bars[3]
colombia_bar.set_color('#FFF832')         # Color de la barra
colombia_bar.set_edgecolor('#E5B029')       # Color del contorno
colombia_bar.set_linewidth(2)           # Ancho del contorno

plt.show()

import matplotlib.pyplot as plt
import numpy as np

y = np.array([134, 549, 72, 70, 40 ,105, 185])
mylabels = ["Argentina", "Brasil", "Chile", "Colombia", "Perú","Venezuela", "Otros"]

plt.title("Generación eléctrica de diferentes paises 2005-2022 (TWh)")

# Generate pie chart and store the returned objects (wedges, texts, etc)
wedges, texts = plt.pie(y, labels=mylabels)


# Access the 'Colombia' wedge (index 3)
colombia_wedge = wedges[3]
# Set color and edgecolor for 'Colombia' slice
colombia_wedge.set_facecolor('#FFF832')
colombia_wedge.set_edgecolor('#E5B029')
colombia_wedge.set_linewidth(2)


plt.show()

import matplotlib.pyplot as plt
import numpy as np

plt.title("Demanda de energía primaria en Sudamerica y Centroamerica, por fuente en Millones de tep (2005-2022)")

x = np.random.normal(614.4, 667.5, 650)

plt.hist(x)
plt.show()

!pip install ydata-profiling

from ydata_profiling import ProfileReport
import pandas as pd

profile = ProfileReport(df, title="Pandas Profiling Report")
profile.to_notebook_iframe()

profile.to_file("report.html")